### ISSUE TITLE
[GIP] Burn all gas fees

### ISSUE THREAD

**Issue by treeder** [gochain/gip#30]
Burn all gas used for transaction fees.

## Overview

Burn all transaction fees in order to reduce inflation. 

## Motivation

Burning gas would reduce GO inflation and potentially even cause deflation after enough volume is reached. 

Prereq: #29 increase fees

The primary goal is to eliminate inflation. By burning gas, we offset the block rewards and at a certain amount of transactions it will be deflationary. At less than 14 tps, rewards will be eliminated depending on the contract gas requirements. Anything over 14 will be deflationary meaning GO’s total supply will decrease. 

## Specification

All gas fees collected in a block are not taken by the node signing the block, and therefore effectively burned.

## Additional Information

Q: how to publicly track burnt gas so we can calculate total supply?

**Comment by smahmoud822** [comment]
Good let's Burn everything and get rid of inflation 1bil go is more than enough

**Comment by timhnc75** [comment]
Even less than 1 billion works

**Comment by jmank88** [comment]
> roughly 14 tps, rewards will be eliminated

My calculations show the equilibrium point at around 33 tps:
Rewards are `7 GO per block`. So it would take `7 GO per block` / `0.042 GO per tx` / `5 seconds per block`=`33.3 tps` (2.5% load)

Here is a chart projecting the total supply over time at various constant loads (if this change were applied in 2 weeks):
![Total Supply at X tps (2)](https://user-images.githubusercontent.com/1194128/97985154-78483080-1d9d-11eb-937b-abdf52a10911.png)
Notice:
- 0 load continues the existing trend of reward inflation without this change.
- 2.5% load levels off around 1,111,369,384 GO.
- 5% load causes _deflation_ roughly mirroring the standard 7 GO reward _inflation_. 
- 10% load causes around 3x the deflation of 5%.
- 50% load quickly burns all tokens in ~18 mos
- Although we can calculate and state the deflation over time in relation to total supply, the actual decrease from the burn does not depend on total supply in any way. A steady constant load and thus burn rate actually produces _accelerating_ deflation as a percent of total supply, since the supply decreases over time.

Here is a table of the change in total supply per block at some of these loads:

load | tps @21000 | @50000 | @200000 | GO/block
| --: | --: | --: | --: | --: |
0.00% | 0 | 0 | 0 | 7.0
2.50% | 33 | 14 | 3 | -0.1
5.00% | 65 | 27 | 7 | -6.9
10.00% | 130 | 55 | 14 | -20.3
50.00% | 650 | 273 | 68 | -129.5
100.00% | 1300 | 546 | 137 | -266.0

**Comment by treeder** [comment]
My calculations were based on a GO20 transfer which cost roughly 0.0001 GO per tx, or 0.1 GO after #29. I think we can safely assume the vast majority of transactions will be smart contract operations like GO20's.  More complex transactions like a swap are 2-3x that and if a lot of transactions were like that it would be about 4tps to hit equilibrium.

**Comment by treeder** [comment]
## Vote Details

start_time:2020-12-10T20:00:00Z
end_time:2020-12-12T20:00:00Z
contract_address:0x6eab94D332E971f0c89f8b4273138FCE8b5dA0C5
choice_1:yes:0xdfb1fFceebCB9b9737C29B8B338D87f196C62e86
choice_2:no:0xD10aF548625E68F97013FaE2d14343EBa46C6952

**Comment by treeder** [comment]
This is going live on mainnet in one week...
